name: Issue Trigger

on:
  issues:
    types: [opened, edited]

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install requests

    - name: Write body to file
      run: |
        echo '${{ github.event.issue.body }}' | sed 's/```//g' > issue_body_raw.json
      
    - name: Run processing script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python .github/generate-theme.py

    - name: Remove Files
      run: |
        rm issue_body_raw.json

    - name: Close issue
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
        -d '{"state":"closed"}' > /dev/null 2>&1
