name: Issue Update

on:
  issues:
    types: [closed, edited]

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install requests argparse

    - name: Write issue body to file
      run: |
        echo '${{ github.event.issue.body }}' | sed 's/```//g' > issue_body_raw.json

    - name: Check if issue was reopened by the same user
      id: check_reopen
      run: |
        if [[ "${{ github.event.action }}" == "edited" && "${{ github.event.issue.state }}" == "closed" && "${{ github.event.issue.user.login }}" == "${{ github.event.sender.login }}" ]]; then
          echo "reopened_by_same_user=true" >> $GITHUB_ENV
        else
          echo "reopened_by_same_user=false" >> $GITHUB_ENV
        fi
        
    - name: Run issue processing script
      if: env.reopened_by_same_user == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python .github/generate-theme.py --update true

    - name: Remove Files
      if: env.reopened_by_same_user == 'true'
      run: |
        rm issue_body_raw.json

    - name: Close issue
      if: env.reopened_by_same_user == 'true' && success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
        -d '{"state":"closed"}' > /dev/null 2>&1
